part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = '/';
  static const MAIN_PAGE = '/main-page';
  static const SIGN_IN = '/sign-in';
  static const SIGN_UP = '/sign-up';
  static const KYC_VERIFICATION = '/kyc-verification';
  static const KYC_VERIFICATION_New = '/kyc-verification_new';
  static const KYC_VERIFICATION_Step2_New = '/kyc-verification_step2_new';
  static const EDIT_PROFILE = '/edit-profile';
  static const CHANGE_PASSWORD = '/change-password';
  static const RESET_PASSWORD = '/reset-password';
  static const SETTINGS = '/settings';
  static const SUPPORT_PAGES = '/support-pages';
  static const CONTACT_US = '/contact-us';
  static const LOAN_PLANS = '/loan-plans';
  static const APPLY_LOAN = '/apply-loan';
  static const ALL_LOAN = '/all-loan';
  static const LOG_DETAILS = '/log-details';
  static const ALL_DPS = '/all-dps';
  static const DPS_PLAN = '/dps-plan';
  static const FDR_PLAN = '/fdr-plan';
  static const ALL_FDR = '/fdr-list';
  static const DEPOSIT = '/deposit';
  static const WIRE_TRANSFER = '/wire-transfer';
  static const ADD_WIRE_TRANSFER = '/add-wire-transfer';
  static const WITHDRAW_LIST = '/withdraw-list';
  static const ADD_WITHDRAW = '/add-withdraw';
  static const TRANSFER_LOG = '/transfer-log';
  static const OTHERS_BANKS = '/others-banks';
  static const OTHERS_BANK_TRANSFER = '/others-bank-transfer';
  static const BENEFICIARY_LIST = '/beneficiary-list';
  static const ADD_BENEFICIARY = '/add-beneficiary';
  static const PAYMENT_PAGE = '/payment-page';
  static const SEND_MONEY = '/send-money';
  static const PRICING_PLAN = '/pricing-plan';
  static const REQUEST_MONEY_LIST = '/request-money-list';
  static const SUBMIT_REQUEST_MONEY = '/submit-request-money';
  static const RECEIVE_REQUEST_MONEY = '/receive-request-money';
  static const MY_REFERRED = '/my-referred';
  static const REFERRER_COMMISSION = '/referrer-commission';
  static const TRANSACTIONS = '/transactions';
  static const BLOGS = '/blogs';
  static const BLOG_DETAILS = '/blog-details';
  static const TICKETS_PAGE = '/tickets-page';
  static const TICKET_DETAILS_PAGE = '/ticket-details-page';
  static const TWO_FA_VERIFICATION = '/two-fa-verification';
}
